"""AI Act Article 50 Compliance Scanner — Deadline: 2. August 2026"""
import asyncio
import logging
import re
import aiohttp

log = logging.getLogger("AIActScanner")

AI_WIDGET_PATTERNS = [
    r"tidio", r"intercom", r"drift", r"zendesk", r"freshchat",
    r"crisp\.chat", r"tawk\.to", r"livechat", r"helpscout",
    r"hubspot.*chat", r"chatbot", r"ai.*assistant", r"gpt",
    r"chatgpt", r"openai", r"claude", r"anthropic",
    r"rebuy", r"frequently.*bought", r"you may also like.*ai",
    r"personali[sz]ed.*recommend", r"ai.*recommend",
    r"__tidio", r"jivo", r"olark", r"userlike",
    r"smartsupp", r"chatra", r"purechat",
]

DISCLOSURE_KEYWORDS = [
    "ki-generiert", "ki-inhalt", "von ki erstellt", "ai generated",
    "generated by ai", "created with ai", "ai-powered",
    "dieser inhalt wurde von ki", "this content was generated",
    "chatbot", "virtual assistant", "ki-assistent",
    "you are chatting with an ai", "du chattest mit einer ki",
]

ARTICLE_50_DISCLOSURE_BANNER = """
<!-- EU AI ACT ART. 50 COMPLIANCE BANNER — GENERATED BY EU-COMPLIANCE-SAAS -->
<div id="ai-act-disclosure" style="
  position:fixed;bottom:0;left:0;right:0;z-index:99999;
  background:#1a1a2e;color:#e0e0e0;font-size:13px;
  padding:10px 20px;display:flex;align-items:center;justify-content:space-between;
  border-top:2px solid #6366f1;font-family:sans-serif;">
  <span>🤖 <strong>KI-Hinweis:</strong> Dieser Shop verwendet KI-gestützte Funktionen (Chatbot, Produktempfehlungen). Gemäß EU-KI-Verordnung Art. 50.</span>
  <button onclick="document.getElementById('ai-act-disclosure').style.display='none'"
    style="background:#6366f1;color:#fff;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;margin-left:20px;">OK</button>
</div>
"""


async def scan_shopify_store(shop_url: str, session: aiohttp.ClientSession) -> dict:
    """Scannt eine Shopify-URL auf AI-Act-Art.-50-Verstöße."""
    result = {
        "shop": shop_url,
        "has_ai_widgets": False,
        "has_disclosure": False,
        "compliant": False,
        "violations": [],
        "widgets_found": [],
        "risk_level": "LOW",
        "fine_risk_eur": 0,
    }
    try:
        headers = {"User-Agent": "EUComplianceBot/1.0 (compliance-check)"}
        async with session.get(f"https://{shop_url}", headers=headers, timeout=aiohttp.ClientTimeout(total=15)) as resp:
            if resp.status != 200:
                return result
            html = await resp.text()
            html_lower = html.lower()

            for pattern in AI_WIDGET_PATTERNS:
                if re.search(pattern, html_lower):
                    result["has_ai_widgets"] = True
                    result["widgets_found"].append(pattern.replace(r".*", "").replace("\\", ""))

            for kw in DISCLOSURE_KEYWORDS:
                if kw in html_lower:
                    result["has_disclosure"] = True
                    break

            if result["has_ai_widgets"] and not result["has_disclosure"]:
                result["violations"].append("Fehlende KI-Offenlegungspflicht (Art. 50 Abs. 1 EU-KI-VO)")
                result["risk_level"] = "HIGH"
                result["fine_risk_eur"] = 15_000_000
            elif result["has_ai_widgets"]:
                result["compliant"] = True
                result["risk_level"] = "LOW"

    except Exception as e:
        log.warning("Scan error for %s: %s", shop_url, e)
    return result


async def generate_compliance_report(shop_url: str) -> dict:
    """Vollständiger Compliance-Report für einen Shop."""
    async with aiohttp.ClientSession() as session:
        scan = await scan_shopify_store(shop_url, session)

    scan["disclosure_banner_html"] = ARTICLE_50_DISCLOSURE_BANNER if not scan["has_disclosure"] else None
    scan["deadline"] = "2026-08-02"
    scan["law_reference"] = "EU-KI-Verordnung (EU) 2024/1689, Art. 50"
    scan["fine_category"] = "Art. 99 Abs. 4 lit. g — bis €15 Mio. oder 3% des weltweiten Jahresumsatzes"
    scan["recommended_action"] = (
        "Sofort AI-Disclosure-Banner einbinden und KI-generierte Inhalte kennzeichnen."
        if not scan["compliant"] else "Shop ist compliant. Weiterhin regelmäßig prüfen."
    )
    return scan


async def bulk_scan_stores(shop_list: list) -> list:
    """Scannt mehrere Shops parallel."""
    async with aiohttp.ClientSession() as session:
        tasks = [scan_shopify_store(shop, session) for shop in shop_list]
        return await asyncio.gather(*tasks, return_exceptions=True)
