#!/usr/bin/env python3
"""
EU AI Act Art. 50 Compliance Suite — SuperMegaBot
Deadline: 2. August 2026 | Bußgeld: bis €15 Mio. / 3% Jahresumsatz
Preis: €49–149/Monat pro Shop

Art. 50 Pflichten:
(1) Chatbots müssen sich als KI offenbaren
(2) Deepfakes/AI-generierte Bilder müssen gekennzeichnet sein
(3) AI-generierter Text muss maschinenlesbar markiert sein
(4) Emotionserkennungs-/Biometrie-Systeme → Offenlegung gegenüber Betroffenen
(5) Risikoklassifizierung für eingesetzte KI-Systeme
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path

import aiohttp
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")
log = logging.getLogger("AIActArt50")

TG_TOKEN    = os.getenv("TELEGRAM_BOT_TOKEN", "")
TG_CHAT     = os.getenv("TELEGRAM_CHAT_ID", "")
ANTHROPIC   = os.getenv("ANTHROPIC_API_KEY", "")
STRIPE_PRICE= os.getenv("AI_ACT_ART50_PRICE_ID", "")
NETLIFY_BASE= os.getenv("BPI_NETLIFY_URL", "https://extraordinary-daffodil-239faa.netlify.app")
STATE_FILE  = Path(__file__).parent.parent / "data" / "ai_act_art50_state.json"

DEADLINE_DATE = "2026-08-02"
DEADLINE_TS   = 1754092800  # 2. August 2026 00:00 UTC

# ── Disclosure-Banner HTML-Template ───────────────────────────────────
ARTICLE_50_DISCLOSURE_BANNER = """<!-- EU AI Act Art. 50 Compliance Banner — generated by SuperMegaBot -->
<div id="ai-disclosure-banner" style="
  position:fixed; bottom:0; left:0; right:0; z-index:99999;
  background:#1a1a2e; color:#e0e0e0; padding:12px 20px;
  font-family:Arial,sans-serif; font-size:13px;
  display:flex; align-items:center; justify-content:space-between;
  border-top:2px solid #00d48a; box-shadow:0 -2px 12px rgba(0,0,0,.3);
">
  <span>
    🤖 <strong>KI-Hinweis (EU AI Act Art. 50):</strong>
    Dieser Chat-Assistent wird von Künstlicher Intelligenz betrieben.
    Sie interagieren mit einem KI-System, nicht mit einer menschlichen Person.
    <a href="/datenschutz#ki-einsatz" style="color:#00d48a;margin-left:8px;">Mehr erfahren →</a>
  </span>
  <button onclick="document.getElementById('ai-disclosure-banner').style.display='none'"
    style="background:none;border:1px solid #555;color:#aaa;padding:4px 10px;cursor:pointer;margin-left:16px;">
    ✕
  </button>
</div>
<script>
// AI Act Art. 50 Compliance — Chatbot-Offenlegung
(function() {
  var shown = sessionStorage.getItem('ai_disclosure_shown');
  if (!shown) { sessionStorage.setItem('ai_disclosure_shown', '1'); }
  // Maschinenlesbare Markierung (Art. 50 Abs. 4)
  document.documentElement.setAttribute('data-ai-generated', 'partial');
  document.documentElement.setAttribute('data-ai-act-compliant', 'art50-2026');
})();
</script>"""

# 5 vorgefertigte Banner-Templates
DISCLOSURE_TEMPLATES = {
    "minimal_de": {
        "name": "Minimal Deutsch",
        "html": '<div class="ai-notice" style="background:#f0f9ff;border-left:4px solid #0066cc;padding:8px 12px;font-size:12px;color:#444;">🤖 KI-Assistent (EU AI Act Art. 50)</div>',
        "compliant": True,
    },
    "minimal_en": {
        "name": "Minimal English",
        "html": '<div class="ai-notice" style="background:#f0f9ff;border-left:4px solid #0066cc;padding:8px 12px;font-size:12px;color:#444;">🤖 AI Assistant (EU AI Act Art. 50)</div>',
        "compliant": True,
    },
    "full_de": {
        "name": "Vollständig Deutsch",
        "html": ARTICLE_50_DISCLOSURE_BANNER,
        "compliant": True,
    },
    "shopify_de": {
        "name": "Shopify-Widget Deutsch",
        "html": '<p style="font-size:11px;color:#888;margin-top:8px;">ℹ️ Dieser Assistent nutzt KI-Technologie (EU AI Act Art. 50). <a href="/pages/datenschutz">Details</a></p>',
        "compliant": True,
    },
    "gdpr_combined": {
        "name": "DSGVO + AI Act kombiniert",
        "html": '<div style="border:1px solid #ddd;border-radius:4px;padding:10px;font-size:12px;color:#555;margin-top:10px;">🔒 Datenschutz · 🤖 KI-Einsatz nach EU AI Act Art. 50 · <a href="/datenschutz">Mehr Info</a></div>',
        "compliant": True,
    },
}

# Art. 50 Checkliste
ART50_CHECKLIST = [
    {"id": 1, "check": "chatbot_disclosure",    "description": "Chatbot offenbart sich als KI (Art. 50 Abs. 1)"},
    {"id": 2, "check": "deepfake_labeling",     "description": "Deepfake/AI-Bilder gekennzeichnet (Art. 50 Abs. 4)"},
    {"id": 3, "check": "machine_readable_mark", "description": "AI-Text maschinenlesbar markiert (Art. 50 Abs. 2)"},
    {"id": 4, "check": "emotion_disclosure",    "description": "Emotionserkennung offengelegt wenn genutzt (Art. 50 Abs. 3)"},
    {"id": 5, "check": "ai_system_register",    "description": "Eingesetzte KI-Systeme dokumentiert"},
]

# Bekannte Chatbot-Widgets / AI-Indiktatoren
AI_WIDGET_SIGNALS = [
    "intercom", "drift", "zendesk", "freshchat", "tidio", "crisp",
    "chatgpt", "openai", "claude", "anthropic", "botpress", "dialogflow",
    "livechat", "tawkto", "hubspot chat", "gorgias", "re:amaze",
    "chat-widget", "chatbot", "ai-assistant", "llm",
    "data-ai", "data-bot", "bot-launcher", "chat-launcher",
]


def _load_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except Exception:
            pass
    return {"registered_shops": [], "scan_results": {}, "last_cycle": 0}


def _save_state(state: dict):
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2, ensure_ascii=False))


async def _tg(msg: str):
    if not TG_TOKEN or not TG_CHAT:
        return
    try:
        async with aiohttp.ClientSession() as s:
            await s.post(
                f"https://api.telegram.org/bot{TG_TOKEN}/sendMessage",
                json={"chat_id": TG_CHAT, "text": msg, "parse_mode": "Markdown"},
                timeout=aiohttp.ClientTimeout(total=8),
            )
    except Exception:
        pass


def get_disclosure_templates() -> dict:
    """5 vorgefertigte Banner-Templates (DE/EN)."""
    return DISCLOSURE_TEMPLATES


async def generate_disclosure_banner(
    shop_url: str = "",
    chatbot_type: str = "generic",
    language: str = "de",
    style: str = "full",
) -> dict:
    """
    Generiert EU AI Act Art. 50 konformes Disclosure-Banner HTML.
    Returns: {html, compliant, chatbot_type, installation_hint}
    """
    days_left = max(0, (DEADLINE_TS - int(time.time())) // 86400)

    if style == "minimal" and language == "en":
        template = DISCLOSURE_TEMPLATES["minimal_en"]
    elif style == "minimal":
        template = DISCLOSURE_TEMPLATES["minimal_de"]
    elif chatbot_type.lower() in ("shopify", "shop"):
        template = DISCLOSURE_TEMPLATES["shopify_de"]
    else:
        template = DISCLOSURE_TEMPLATES["full_de"]

    # Customization
    html = template["html"]
    if shop_url:
        html = html.replace("/datenschutz#ki-einsatz", f"{shop_url.rstrip('/')}/datenschutz#ki-einsatz")

    return {
        "ok": True,
        "html": html,
        "compliant": True,
        "chatbot_type": chatbot_type,
        "deadline": DEADLINE_DATE,
        "days_remaining": days_left,
        "installation_hint": (
            "Füge diesen HTML-Code in deinen Shop-Theme-Footer ein. "
            "Shopify: Online Store → Themes → Edit Code → theme.liquid → vor </body>"
        ),
        "legal_basis": "EU AI Act Art. 50 Abs. 1 — Pflicht ab 2. August 2026",
        "fine_if_missing": "bis €15.000.000 oder 3% des weltweiten Jahresumsatzes",
    }


async def scan_website_for_ai_content(url: str) -> dict:
    """
    Scannt eine Website auf AI-Widgets und fehlende Art.-50-Disclosures.
    Returns: {found_ai_widgets, compliance_score, missing_disclosures, checklist}
    """
    if not url.startswith("http"):
        url = "https://" + url

    found_widgets   = []
    has_disclosure  = False
    html_content    = ""

    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(
                url,
                headers={"User-Agent": "Mozilla/5.0 (EU-AI-Act-Compliance-Scanner/1.0)"},
                timeout=aiohttp.ClientTimeout(total=15),
                ssl=False,
            ) as r:
                if r.status == 200:
                    html_content = (await r.text())[:50000]
    except Exception as e:
        return {
            "ok": False, "url": url, "error": str(e),
            "compliance_score": 0, "found_ai_widgets": [],
            "missing_disclosures": ["Website nicht erreichbar"],
        }

    html_lower = html_content.lower()

    # AI-Widgets suchen
    for signal in AI_WIDGET_SIGNALS:
        if signal in html_lower:
            found_widgets.append(signal)

    # Disclosure-Hinweise suchen
    disclosure_signals = [
        "ai act", "eu ai", "künstliche intelligenz", "artificial intelligence",
        "ki-assistent", "ai-assistant", "chatbot-hinweis", "bot-disclosure",
        "data-ai-act", "data-ai-generated",
    ]
    for sig in disclosure_signals:
        if sig in html_lower:
            has_disclosure = True
            break

    # Compliance-Checkliste
    checklist = []
    for item in ART50_CHECKLIST:
        passed = False
        if item["check"] == "chatbot_disclosure":
            passed = has_disclosure or not found_widgets
        elif item["check"] == "machine_readable_mark":
            passed = 'data-ai-act-compliant' in html_lower
        else:
            passed = False  # konservativ — manuelle Prüfung nötig

        checklist.append({**item, "passed": passed, "manual_check": not passed})

    passed_count = sum(1 for c in checklist if c["passed"])
    score        = round(passed_count / len(checklist) * 100)

    missing = []
    if found_widgets and not has_disclosure:
        missing.append(f"Chatbot-Disclosure fehlt (gefunden: {', '.join(found_widgets[:3])})")
    if 'data-ai-act-compliant' not in html_lower:
        missing.append("Maschinenlesbare KI-Markierung (data-ai-act-compliant) fehlt")
    if not missing and not found_widgets:
        missing.append("Kein KI-Chatbot gefunden — kein Art.-50-Risiko bei aktuellem Stand")

    return {
        "ok":                   True,
        "url":                  url,
        "found_ai_widgets":     list(set(found_widgets)),
        "has_disclosure":       has_disclosure,
        "compliance_score":     score,
        "missing_disclosures":  missing,
        "checklist":            checklist,
        "scan_timestamp":       datetime.now(timezone.utc).isoformat(),
        "risk_level":           "HOCH" if (found_widgets and not has_disclosure) else "NIEDRIG",
        "days_to_deadline":     max(0, (DEADLINE_TS - int(time.time())) // 86400),
    }


async def generate_compliance_report(shop_domain: str) -> dict:
    """
    Vollständiger Art.-50-Compliance-Report für einen Shop (JSON).
    Kann als PDF-Basis genutzt werden.
    """
    url = f"https://{shop_domain}" if not shop_domain.startswith("http") else shop_domain
    scan = await scan_website_for_ai_content(url)
    banner = await generate_disclosure_banner(shop_url=url, chatbot_type="shopify")
    days = max(0, (DEADLINE_TS - int(time.time())) // 86400)

    status = "NICHT KONFORM" if scan.get("found_ai_widgets") and not scan.get("has_disclosure") else "PRÜFUNG ERFORDERLICH"

    report = {
        "report_type":       "EU AI Act Art. 50 Compliance Report",
        "generated_at":      datetime.now(timezone.utc).isoformat(),
        "shop":              shop_domain,
        "compliance_status": status,
        "score":             scan.get("compliance_score", 0),
        "deadline":          DEADLINE_DATE,
        "days_remaining":    days,
        "urgency":           "DRINGEND" if days < 30 else "MITTEL",
        "scan_results":      scan,
        "banner_html":       banner.get("html", ""),
        "action_items": [
            {
                "priority": "SOFORT",
                "action":   "Disclosure-Banner in Shop-Theme einfügen",
                "details":  banner.get("installation_hint", ""),
                "deadline": DEADLINE_DATE,
            },
            {
                "priority": "HOCH",
                "action":   "Maschinenlesbare Markierung (data-ai-act-compliant) setzen",
                "details":  "Im <html>-Tag: data-ai-act-compliant='art50-2026'",
                "deadline": DEADLINE_DATE,
            },
            {
                "priority": "MITTEL",
                "action":   "Datenschutzerklärung um KI-Einsatz ergänzen",
                "details":  "Abschnitt 'Einsatz von KI-Systemen' hinzufügen",
                "deadline": DEADLINE_DATE,
            },
        ],
        "legal_references": [
            "EU AI Act Art. 50 Abs. 1 — Chatbot-Offenlegungspflicht",
            "EU AI Act Art. 50 Abs. 2 — Maschinenlesbare Markierung",
            "EU AI Act Art. 99(4)(g) — Bußgeldkategorie €15 Mio./3%",
        ],
        "stripe_upgrade_link": f"https://buy.stripe.com/{os.getenv('AI_ACT_ART50_STRIPE_LINK', '')}" if os.getenv('AI_ACT_ART50_STRIPE_LINK') else "",
    }
    return report


async def run_art50_cycle() -> dict:
    """
    Scheduler-Einstieg: alle registrierten Shops scannen.
    Schickt TG-Alert bei nicht-konformen Shops.
    """
    state    = _load_state()
    shops    = state.get("registered_shops", [])
    results  = {}
    alerts   = []

    for shop in shops:
        try:
            scan = await scan_website_for_ai_content(shop)
            results[shop] = scan
            if scan.get("found_ai_widgets") and not scan.get("has_disclosure"):
                alerts.append(f"⚠️ {shop} — Chatbot ohne Disclosure!")
        except Exception as e:
            results[shop] = {"ok": False, "error": str(e)}

    days = max(0, (DEADLINE_TS - int(time.time())) // 86400)

    if alerts:
        msg = (
            f"🚨 *EU AI Act Art. 50 — {len(alerts)} Verstöße gefunden!*\n"
            f"Deadline: {DEADLINE_DATE} (noch {days} Tage)\n"
            f"Bußgeld: bis €15 Mio. / 3% Umsatz\n\n"
            + "\n".join(alerts[:10])
        )
        await _tg(msg)
    elif days <= 30:
        await _tg(
            f"⏰ *EU AI Act Art. 50 — Deadline in {days} Tagen!*\n"
            f"({DEADLINE_DATE}) — alle {len(shops)} Shops geprüft, keine Akutprobleme."
        )

    state["scan_results"] = results
    state["last_cycle"]   = int(time.time())
    _save_state(state)

    return {
        "ok":      True,
        "shops":   len(shops),
        "alerts":  len(alerts),
        "days":    days,
        "results": results,
    }


async def get_status() -> dict:
    state = _load_state()
    days  = max(0, (DEADLINE_TS - int(time.time())) // 86400)
    return {
        "deadline":          DEADLINE_DATE,
        "days_remaining":    days,
        "urgency":           "DRINGEND" if days < 30 else "MITTEL",
        "registered_shops":  len(state.get("registered_shops", [])),
        "price_range":       "€49–149/Monat",
        "stripe_price_id":   STRIPE_PRICE,
        "fine_risk":         "bis €15 Mio. oder 3% Jahresumsatz",
        "legal_basis":       "EU AI Act Art. 50 Abs. 1–4",
    }
