#!/bin/bash

# Dodge Challenger 2010 V6 3.5L OBD Diagnostic Launcher
# For intermittent starting issues (heat-related)

echo "=========================================="
echo "Dodge Challenger 2010 V6 3.5L Diagnose"
echo "=========================================="
echo ""
echo "Problem: Intermittierender Start, Motor geht nach Fahrt aus"
echo "Verdacht: Hitzebedingtes Problem"
echo ""
echo "Wahrscheinliche Ursachen:"
echo "1. Crankshaft Position Sensor (Kurbelwellensensor) - P0335"
echo "2. Camshaft Position Sensor (Nockenwellensensor) - P0340"
echo "3. Fuel Pump Module (Kraftstoffpumpe) - P0230"
echo "4. ASD Relay (Auto Shutdown Relay)"
echo "5. Ignition Coils (Zündspulen)"
echo ""
echo "=========================================="
echo "Nächste Schritte:"
echo "=========================================="
echo ""
echo "1. ThinkDiag mit Dodge Challenger verbinden"
echo "2. Full System Scan durchführen"
echo "3. Live-Daten überwachen bei warmem Motor"
echo "4. Besonders prüfen:"
echo "   - Crankshaft Position Sensor Signal"
echo "   - Camshaft Position Sensor Signal"
echo "   - Fuel Pressure"
echo "   - Ignition Timing"
echo ""
echo "Wichtige Fehlercodes:"
echo "P0335 - Kurbelwellensensor A-Kurve"
echo "P0340 - Nockenwellensensor Bank 1"
echo "P0230 - Kraftstoffpumpen-Relay"
echo "P0128 - Thermostat"
echo "P0300-P0306 - Zündaussetzer"
echo ""
echo "=========================================="
echo "Bereit für Diagnose mit ThinkDiag"
echo "=========================================="
