#!/usr/bin/env python3
"""
ThinkDiag+ auf iPhone/iPad - Schritt-fuer-Schritt
"""

print("=" * 70)
print("  THINKDIAG+ AUF iPHONE/iPAD")
print("  Dodge Challenger 2010 V6")
print("=" * 70)
print()

print("[SCHRITT 1] ThinkDiag+ installieren")
print("-" * 70)
print("  1. App Store oeffnen")
print("  2. Suche: 'ThinkDiag+'")
print("  3. App von ThinkCar installieren")
print("  4. App starten")
print()

print("[SCHRITT 2] ThinkDiag 2 vorbereiten")
print("-" * 70)
print("  Im Auto:")
print("  1. ThinkDiag 2 in OBD-Port stecken")
print("     (unter dem Armaturenbrett, links vom Lenkrad)")
print("  2. Zündung auf ON drehen (2 Klicks)")
print("  3. NICHT starten!")
print("  4. Warte 10-20 Sekunden")
print("  5. LED am ThinkDiag 2 sollte leuchten/blinken")
print()

print("[SCHRITT 3] Bluetooth verbinden")
print("-" * 70)
print("  Auf iPhone/iPad:")
print("  1. Einstellungen -> Bluetooth")
print("  2. Suche 'ThinkDiag' oder 'TD2'")
print("  3. Tippe zum Verbinden")
print("  4. Warte bis 'Verbunden' steht")
print()

print("[SCHRITT 4] ThinkDiag+ App einrichten")
print("-" * 70)
print("  In der App:")
print("  1. App starten")
print("  2. Account erstellen oder einloggen")
print("  3. 'Diagnose' oder 'Scan' waehlen")
print("  4. Marke: Dodge")
print("  5. Modell: Challenger")
print("  6. Jahr: 2010")
print("  7. Motor: 3.5L V6")
print("  8. 'Verbinden' klicken")
print()

print("[SCHRITT 5] Diagnose durchfuehren")
print("-" * 70)
print("  In der App:")
print("  1. 'Systemdiagnose' oder 'Alle Systeme'")
print("  2. Warte bis Scan abgeschlossen ist")
print("  3. Pruefe Fehlercodes (DTC)")
print("  4. Pruefe Live-Daten:")
print("     - Motordrehzahl (RPM)")
print("     - Kuehlmitteltemperatur")
print("     - Kraftstoffdruck")
print("     - Kurbelwellensensor")
print()

print("[SCHRITT 6] Problem analysieren")
print("-" * 70)
print("  Fuer 'Anlasser geht, Motor startet nicht':")
print()
print("  WICHTIGE FEHLERCODES:")
print("    P0335 - Kurbelwellensensor defekt")
print("    P0340 - Nockenwellensensor defekt")
print("    P0230 - Kraftstoffpumpenrelais")
print("    P0562 - Batteriespannung zu niedrig")
print("    P0601 - PCM interner Fehler")
print()
print("  LIVE-DATEN PRUEFEN:")
print("    - RPM beim Anlassen (sollte 200-300 sein)")
print("    - Kraftstoffdruck (sollte 3-5 bar)")
print("    - Kurbelwellensignal (sollte wechseln)")
print()

print("=" * 70)
print("  TIPP: Screenshot der Fehlercodes machen!")
print("  Dann koennen wir die Codes zusammen analysieren.")
print("=" * 70)

print()
input("ENTER zum Beenden")
