#!/usr/bin/env python3
"""
ELM327 KAUF-EMPFEHLUNG fuer Dodge Challenger 2010
"""

print("=" * 65)
print("  ELM327 KAUF-EMPFEHLUNG")
print("  fuer Dodge Challenger 2010 V6")
print("=" * 65)
print()

print("[WARUM brauchst du einen neuen Adapter?]")
print("-" * 65)
print("  Dein MINI-VCI J2534 ist ein TOYOTA/Lexus-Tool.")
print("  Er spricht ein anderes Protokoll als dein Dodge.")
print()

print("[EMPFOHLENE ADAPTER]")
print("-" * 65)
print()
print("  1. VEEPAK WiFi OBD2 (~18€)")
print("     - Kein Treiber noetig")
print("     - Mac verbindet sich per WLAN")
print("     - Funktioniert sofort mit allen Tools")
print("     - Suche: 'Veepeak WiFi OBD2' auf Amazon/Ebay")
print()
print("  2. OBDLink LX Bluetooth (~45€)")
print("     - Premium Qualitaet")
print("     - Bluetooth Low Energy")
print("     - Sehr zuverlaessig")
print("     - Suche: 'OBDLink LX' auf Amazon")
print()
print("  3. Beliebiger ELM327 USB (~12€)")
print("     - Braucht evtl. Treiber (FTDI/CH340)")
print("     - Guenstigste Option")
print("     - Suche: 'ELM327 USB Mac' auf Amazon")
print()

print("[WO KAUFEN?]")
print("-" * 65)
print("  Amazon.de:")
print("    https://www.amazon.de/s?k=ELM327+WiFi+iOS")
print()
print("  Ebay.de:")
print("    https://www.ebay.de/sch/i.html?_nkw=ELM327+WiFi+Mac")
print()
print("  OBDLink direkt:")
print("    https://www.obdlink.com/lx-bluetooth/")
print()

print("[WICHTIG: Vermeide billige Klone!]")
print("-" * 65)
print("  Kaufen:")
print("    ✅ OBDLink (qualitativ)")
print("    ✅ Veepeak (guter Mittelweg)")
print("    ✅ BAFX (bekannte Marke)")
print()
print("  Vermeiden:")
print("    ❌ Unbekannte Marken unter 10€")
print("    ❌ 'PIC18F25K80' Chips (instabil)")
print("    ❌ Adapter ohne CE/FCC Zertifizierung")
print()

print("=" * 65)
print("  Sobald der neue Adapter da ist:")
print("  1. In den OBD2-Port stecken (unterm Lenkrad)")
print("  2. Zündung auf ON")
print("  3. Doppelklick auf '10-dodge-autoscan.app'")
print("  4. Fertig!")
print("=" * 65)

print("\nENTER zum Beenden")
input()
