#!/usr/bin/env python3
"""
KOMPLETT SETUP - Alle alternativen Software-Optionen
BlueStacks + Diagzone + X-Diag + Prodiag + ThinkDiag+
"""

print("=" * 70)
print("  KOMPLETT SETUP - ALLE ALTERNATIVEN")
print("  ThinkDiag 2 + BlueStacks + Alle Software-Optionen")
print("=" * 70)
print()

print("[SCHRITT 1] BlueStacks installieren")
print("-" * 70)
print("  1. Doppelklick auf:")
print("     /Users/rudolfsarkany/Downloads/BlueStacksInstaller_5.21.770.7524_*.pkg")
print("  2. Folge dem Installer")
print("  3. BlueStacks in Applications installieren")
print("  4. Installation abwarten (5-10 Minuten)")
print()

print("[SCHRITT 2] BlueStacks starten")
print("-" * 70)
print("  1. Applications -> BlueStacks öffnen")
print("  2. Warte 30-60 Sekunden bis geladen")
print("  3. Google Account einloggen")
print()

print("[SCHRITT 3] Alle Software-Optionen installieren")
print("-" * 70)
print("  Im Play Store:")
print()
print("  [A] Diagzone (Kostenlos)")
print("      1. Suche: 'Diagzone'")
print("      2. Installieren")
print("      3. App starten")
print()
print("  [B] X-Diag (Professionell)")
print("      1. Suche: 'X-Diag' oder 'Xdiag'")
print("      2. Installieren")
print("      3. App starten")
print()
print("  [C] Prodiag")
print("      1. Suche: 'Prodiag'")
print("      2. Installieren")
print("      3. App starten")
print()
print("  [D] ThinkDiag+ (Original)")
print("      1. Suche: 'ThinkDiag+'")
print("      2. Installieren")
print("      3. App starten")
print()

print("[SCHRITT 4] Bluetooth aktivieren")
print("-" * 70)
print("  In BlueStacks:")
print("  1. Einstellungen (Zahnrad)")
print("  2. Bluetooth aktivieren")
print("  3. ThinkDiag 2 pairen")
print("     - Adresse: DC:0D:30:84:4F:C2")
print("     - PIN: 0000 oder 1234")
print()

print("[SCHRITT 5] ThinkDiag 2 vorbereiten")
print("-" * 70)
print("  Im Auto:")
print("  1. ThinkDiag 2 in OBD-Port stecken (ist schon drin)")
print("  2. Zündung auf ON (nicht starten)")
print("  3. Warte 10-20 Sekunden")
print("  4. LED sollte leuchten/blinken")
print()

print("[SCHRITT 6] Diagnose mit ALLEN Apps testen")
print("-" * 70)
print("  Für jede App:")
print()
print("  1. App öffnen")
print("  2. 'Diagnose' oder 'Scan' wählen")
print("  3. Marke: Dodge")
print("  4. Modell: Challenger")
print("  5. Jahr: 2010")
print("  6. Motor: 3.5L V6")
print("  7. 'Verbinden' klicken")
print("  8. ThinkDiag 2 aus Bluetooth-Liste wählen")
print("  9. Diagnose starten")
print("  10. Fehlercodes lesen")
print("  11. Screenshot machen")
print()

print("[SCHRITT 7] Ergebnisse vergleichen")
print("-" * 70)
print("  Prüfe welche App am besten funktioniert:")
print("  - Diagzone: Kostenlos, einfach")
print("  - X-Diag: Professionell, mehr Funktionen")
print("  - Prodiag: Mittelklasse")
print("  - ThinkDiag+: Original, zuverlässig")
print()

print("=" * 70)
print("  EMPFEHLUNG:")
print("  Starte mit Diagzone (kostenlos)")
print("  Wenn nicht zufrieden -> X-Diag probieren")
print("=" * 70)

print()
input("ENTER zum Beenden")
