#!/usr/bin/env python3
"""
BlueStacks Manuelle Installation - Schritt-fuer-Schritt
"""

print("=" * 70)
print("  BLUESTACKS MANUELLE INSTALLATION")
print("  Fuer ThinkDiag 2 auf Mac")
print("=" * 70)
print()

print("[SCHRITT 1] BlueStacks herunterladen")
print("-" * 70)
print("  Oeffne im Browser:")
print("  https://www.bluestacks.com/download.html")
print()
print("  Klicke auf 'Download BlueStacks 5 for Mac'")
print("  Warte bis Download fertig ist (ca. 600MB)")
print()

print("[SCHRITT 2] BlueStacks installieren")
print("-" * 70)
print("  1. Oeffne den Downloads-Ordner")
print("  2. Doppelklick auf BlueStacks.dmg")
print("  3. Ziehe BlueStacks.app in Applications")
print("  4. Warte bis Installation fertig ist")
print()

print("[SCHRITT 3] BlueStacks starten")
print("-" * 70)
print("  1. Oeffne Applications")
print("  2. Doppelklick auf BlueStacks")
print("  3. Warte 30-60 Sekunden bis geladen")
print()

print("[SCHRITT 4] ThinkDiag Software installieren")
print("-" * 70)
print("  In BlueStacks:")
print("  1. Play Store oeffnen")
print("  2. Google Account einloggen")
print("  3. Suche: 'X-Diag' ODER 'ThinkDiag+'")
print("  4. Installieren")
print()

print("[SCHRITT 5] ThinkDiag 2 verbinden")
print("-" * 70)
print("  Im Auto:")
print("  1. ThinkDiag 2 in OBD-Port stecken")
print("  2. Zündung auf ON (nicht starten)")
print()
print("  In BlueStacks:")
print("  3. Einstellungen -> Bluetooth aktivieren")
print("  4. ThinkDiag 2 pairen")
print("  5. App starten -> Dodge -> Challenger -> 2010")
print("  6. Diagnose starten")
print()

print("=" * 70)
print("  ALTERNATIVE: iPhone/iPad")
print("=" * 70)
print()
print("Wenn du ein iPhone/iPad hast:")
print("  1. App Store -> 'ThinkDiag+' suchen")
print("  2. Installieren")
print("  3. Bluetooth aktivieren")
print("  4. ThinkDiag 2 pairen")
print("  5. Dodge Challenger 2010 auswählen")
print("  6. Diagnose starten")
print()
print("Das ist viel einfacher als BlueStacks!")
print("=" * 70)

print()
input("ENTER zum Beenden")
