#!/usr/bin/env python3
"""
ThinkDiag 2 - LOESUNGEN (ohne langen Scan)
"""

print("=" * 70)
print("  THINKDIAG 2 - DEINE LOESUNGEN")
print("=" * 70)
print()

print("STATUS:")
print("-" * 70)
print("  ThinkDiag 2:  VERBUNDEN als /dev/cu.988430957800")
print("  Protokoll:    PROPRIETAER (nur mit ThinkDiag+ App)")
print("  ELM327-Modus: NICHT verfuegbar")
print()

print("=" * 70)
print("  OPTION 1: Android-Emulator auf Mac")
print("=" * 70)
print()
print("  Schritte:")
print("    1. BlueStacks herunterladen:")
print("       https://www.bluestacks.com/download.html")
print("    2. .dmg installieren")
print("    3. Google-Konto einrichten")
print("    4. Play Store -> 'ThinkDiag+' installieren")
print("    5. Mac Bluetooth -> ThinkDiag 2 PAIREN")
print("    6. BlueStacks Einstellungen -> Bluetooth aktivieren")
print("    7. In ThinkDiag+ App -> Auto auswaehlen -> Diagnose starten")
print()
print("  Vorteil: Du nutzt die ORIGINALE App mit ALLEN Funktionen")
print("  Nachteil: Setup dauert 30-60 Minuten")
print()

print("=" * 70)
print("  OPTION 2: Andere OBD-App testen")
print("=" * 70)
print()
print("  Manche Apps unterstuetzen verschiedene Adapter:")
print()
print("    A) OBD Auto Doctor (Mac App Store)")
print("       - Suche 'OBD Auto Doctor' im Mac App Store")
print("       - Kostenlos testen")
print("       - ThinkDiag 2 in OBD-Port stecken")
print("       - App starten -> Verbinden -> pruefen")
print()
print("    B) Car Scanner (iOS/Android)")
print("       - Sehr gute App, viele Adapter unterstuetzt")
print("       - Koennte ThinkDiag 2 erkennen")
print()
print("    C) FORScan (Windows/Mac mit Wine)")
print("       - Fuer Ford/Dodge/Lincoln/Mercury")
print("       - Sehr leistungsstark")
print("       - Koennte ThinkDiag 2 unterstuetzen")
print()

print("=" * 70)
print("  OPTION 3: ThinkDiag+ direkt auf iPhone/iPad")
print("=" * 70)
print()
print("  Wenn du ein iPhone/iPad hast:")
print("    1. App Store -> 'ThinkDiag+' suchen")
print("    2. Installieren")
print("    3. ThinkDiag 2 in OBD-Port stecken")
print("    4. Bluetooth pairen")
print("    5. App starten -> Dodge Challenger 2010 waehlen")
print("    6. Diagnose durchfuehren")
print()
print("  Vorteil: Schnellste Loesung!")
print("  Nachteil: Basis-Funktionen kostenlos, erweitert kostenpflichtig")
print()

print("=" * 70)
print("  OPTION 4: Physische Diagnose (ohne Elektronik)")
print("=" * 70)
print()
print("  Fuer dein Problem 'Anlasser geht, Motor startet nicht':")
print()
print("    1. KRAFTSTOFFPUMPE pruefen:")
print("       - Zündung AN (nicht starten)")
print("       - Hoeren ob Pumpe im Tank surrt (3-5 Sekunden)")
print("       - Wenn NEIN: Sicherung/Relais pruefen")
print()
print("    2. ZUENDKERZEN pruefen:")
print("       - Eine rausschrauben")
print("       - An Masse halten")
print("       - Anlassen -> Funkenflug sehen?")
print()
print("    3. BATTERIE-Spannung:")
print("       - Multimeter auf Batterieklemmen")
print("       - Beim Anlassen: Spannung unter 10V?")
print("       - Wenn JA: Batterie zu schwach")
print()

print("=" * 70)
print("  MEINE EMPFEHLUNG:")
print("=" * 70)
print()
print("  1. Option 3 (iPhone) oder Option 1 (BlueStacks)")
print("     -> ThinkDiag+ ist DIE Software fuer deinen Adapter")
print()
print("  2. ODER: Option 4 (physische Checks)")
print("     -> Kostet nichts, braucht keinen Adapter")
print()

print("=" * 70)
input("ENTER zum Beenden")
