#!/usr/bin/env python3
"""
ThinkDiag 2 - Verbindungs-Guide fuer Dodge Challenger 2010
Schritt-fuer-Schritt Anleitung
"""

print("=" * 70)
print("  THINKDIAG 2 - VERBINDUNGS-GUIDE")
print("  Dodge Challenger 2010 V6")
print("=" * 70)
print()

print("[SCHRITT 1] ThinkDiag 2 im Auto anschliessen")
print("-" * 70)
print("  1. Steige in den Dodge Challenger ein")
print("  2. Suche den OBD2-Port:")
print("     -> UNTER dem Armaturenbrett, links vom Lenkrad")
print("     -> ODER unter der Lenksaeule Verkleidung")
print("     -> ODER in der Fussraum-Verkleidung auf Fahrerseite")
print()
print("  3. Stecke den ThinkDiag 2 in den OBD2-Port")
print("     (16-poliger Stecker, nur in einer Richtung moeglich)")
print()
print("  4. LED am ThinkDiag 2 sollte leuchten/blinken")
print()

print("[SCHRITT 2] Zündung vorbereiten")
print("-" * 70)
print("  1. Autoschluessel einstecken")
print("  2. Zündung auf 'ON' drehen (2 Klicks)")
print("  3. ABER NICHT STARTEN!")
print("  4. Warte 10-20 Sekunden")
print("  5. Motor-Kontrollleuchte sollte leuchten (normal)")
print()

print("[SCHRITT 3] Verbindung herstellen")
print("-" * 70)
print()
print("  WAeHLE DEINE PLATTFORM:")
print()

print("  [A] iPhone / iPad")
print("      1. Einstellungen -> Bluetooth")
print("      2. Suche 'ThinkDiag' oder 'TD2'")
print("      3. Tippe zum Verbinden")
print("      4. Oeffne ThinkDiag+ App")
print("      5. Tippe 'Diagnose starten'")
print("      6. Waehle: Dodge -> Challenger -> 2010")
print()

print("  [B] Android (inkl. BlueStacks auf Mac)")
print("      1. Einstellungen -> Bluetooth / Verbindung")
print("      2. Suche 'ThinkDiag' oder 'TD2'")  
print("      3. Tippe zum Koppeln (PIN: 0000 oder 1234)")
print("      4. Oeffne ThinkDiag+ App")
print("      5. Tippe 'Verbinden'")
print("      6. Waehle: Dodge -> Challenger -> 2010")
print()

print("  [C] KABEL-Verbindung (USB)")
print("      1. Kabel vom ThinkDiag 2 zu USB-Port/Mac")
print("      2. ThinkDiag+ App oeffnen")
print("      3. App erkennt Kabel automatisch")
print("      4. Waehle: Dodge -> Challenger -> 2010")
print()

print("[SCHRITT 4] Diagnose durchfuehren")
print("-" * 70)
print("  In der ThinkDiag+ App:")
print()
print("  1. 'Systemdiagnose' oder 'Alle Systeme'")
print("  2. Warte bis Scan abgeschlossen ist")
print("  3. Pruefe Ergebnisse:")
print()
print("     [FEHLERCODES] (DTC - Diagnostic Trouble Codes)")
print("     -> Rote Codes = Kritisch, sofort beheben")
print("     -> Gelbe Codes = Warnung, beobachten")
print("     -> Tippe auf Code fuer Details")
print()
print("     [LIVE-DATEN]")
print("     -> Motordrehzahl (RPM)")
print("     -> Kuehlmitteltemperatur")
print("     -> Ansauglufttemperatur")
print("     -> Zuendungszeitpunkt")
print("     -> Spritzung (Fuel Trim)")
print()

print("[SCHRITT 5] Problem 'Anlasser geht, Motor startet nicht'")
print("-" * 70)
print("  In ThinkDiag+ pruefe:")
print()
print("  -> Fehlercodes lesen (besonders: P0xxx, B0xxx)")
print("  -> Live-Daten: RPM beim Anlassen (sollte 200-300 sein)")
print("  -> Live-Daten: Kraftstoffdruck (sollte 3-5 bar)")
print("  -> Live-Daten: Kurbelwellensensor (sollte Signale zeigen)")
print()
print("  HAeufige Ursachen fuer Dodge Challenger 2010:")
print("    P0335 - Kurbelwellensensor defekt")
print("    P0340 - Nockenwellensensor defekt")  
print("    P0230 - Kraftstoffpumpenrelais")
print("    P0562 - Batteriespannung zu niedrig")
print("    P0601 - PCM interner Fehler")
print()

print("=" * 70)
print("  HINWEIS: Screenshot der Fehlercodes machen!")
print("  Dann koennen wir die Codes zusammen analysieren.")
print("=" * 70)

print()
input("ENTER zum Beenden")
