module.exports = {
  apps: [
    {
      name: "supermegabot",
      script: "python3",
      args: "dashboard/server.py",
      cwd: "/Users/rudolfsarkany/supermegabot",
      interpreter: "none",
      env: { PORT: 8888 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/supermegabot.log",
    },
    {
      name: "telegram-bot",
      script: "node",
      args: "server.js",
      cwd: "/Users/rudolfsarkany/Library/Mobile Documents/com~apple~CloudDocs/Documents/GitHub/telegram-automation-bot",
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/telegram-bot-pm2.log",
    },
    {
      name: "cratorhub",
      script: "npx",
      args: "tsx server.ts",
      cwd: "/Users/rudolfsarkany/Library/Mobile Documents/com~apple~CloudDocs/Documents/GitHub/digifabrik",
      interpreter: "none",
      env: { PORT: 3000 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/cratorhub-pm2.log",
    },
    {
      name: "windsurf-shopify",
      script: "npm",
      args: "start",
      cwd: "/Users/rudolfsarkany/windsurf-shopify-suite",
      interpreter: "none",
      env: { PORT: 3001 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/windsurf-shopify-pm2.log",
    },
    {
      name: "password-sync",
      script: "npm",
      args: "start",
      cwd: "/Users/rudolfsarkany/password-sync-suite/web-app",
      interpreter: "none",
      env: { PORT: 3005 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/password-sync-pm2.log",
    },
    {
      name: "windsurf-autoheal",
      script: "npm",
      args: "start",
      cwd: "/Users/rudolfsarkany/windsurf-auto-heal",
      interpreter: "none",
      env: { AUTO_HEAL_PORT: 9000 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/windsurf-autoheal-pm2.log",
    },
    {
      name: "windsurf-api-gateway",
      script: "node",
      args: "src/index.js",
      cwd: "/Users/rudolfsarkany/windsurf-api-gateway",
      interpreter: "none",
      env: { PORT: 8080 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/windsurf-api-gateway-pm2.log",
    },
    {
      name: "windsurf-telegram-bot",
      script: "npm",
      args: "start",
      cwd: "/Users/rudolfsarkany/windsurf-telegram-bot",
      interpreter: "none",
      env: { PORT: 8000 },
      restart_delay: 5000,
      kill_timeout: 5000,
      max_restarts: 10,
      log_file: "/tmp/windsurf-telegram-bot-pm2.log",
    },
    {
      name: "windsurf-monitor",
      script: "node",
      args: "windsurf-monitoring.js",
      cwd: "/Users/rudolfsarkany",
      interpreter: "none",
      restart_delay: 10000,
      kill_timeout: 5000,
      max_restarts: 5,
      log_file: "/tmp/windsurf-monitor-pm2.log",
    },
  ],
};
