#!/bin/bash
# RudiBot Erweiterungs-Script für zusätzliche APIs

echo "🚀 RudiBot API Erweiterung"
echo "═══════════════════════════════════════════"

# Phase 1: WhatsApp Business API (HIGHEST PRIORITY)
echo ""
echo "📱 Phase 1: WhatsApp Business API"
echo "=================================="
echo "1. Meta Business Account erstellen: https://business.facebook.com"
echo "2. WhatsApp Business App einrichten"
echo "3. Phone Number ID und Access Token erhalten"
echo ""
echo "Benötigte .env Variablen:"
echo "WHATSAPP_PHONE_ID=123456789"
echo "WHATSAPP_ACCESS_TOKEN=EAAD..."
echo "WHATSAPP_WEBHOOK_VERIFY_TOKEN=secret_string"
echo ""

# Phase 2: Discord Bot API
echo "🎮 Phase 2: Discord Bot API"
echo "=========================="
echo "1. Discord Developer Portal: https://discord.com/developers/applications"
echo "2. New Application → Bot erstellen"
echo "3. Bot Token kopieren"
echo "4. Bot zu Server einladen"
echo ""
echo "Benötigte .env Variablen:"
echo "DISCORD_BOT_TOKEN=MTI..."
echo "DISCORD_CLIENT_ID=123456789"
echo "DISCORD_CLIENT_SECRET=secret"
echo ""

# Phase 3: Twitter/X API v2
echo "🐦 Phase 3: Twitter/X API v2"
echo "============================"
echo "1. Twitter Developer Portal: https://developer.twitter.com"
echo "2. New Project → App erstellen"
echo "3. Bearer Token generieren"
echo ""
echo "Benötigte .env Variablen:"
echo "TWITTER_BEARER_TOKEN=AAAAA..."
echo "TWITTER_API_KEY=abc123"
echo "TWITTER_API_SECRET=def456"
echo ""

# Phase 4: Instagram Basic Display
echo "📷 Phase 4: Instagram Basic Display"
echo "===================================="
echo "1. Facebook Developer Portal"
echo "2. Instagram Basic Display App"
echo "3. Access Token generieren"
echo ""
echo "Benötigte .env Variablen:"
echo "INSTAGRAM_ACCESS_TOKEN=IGQVJ..."
echo "INSTAGRAM_APP_ID=123456789"
echo "INSTAGRAM_APP_SECRET=secret"
echo ""

# Phase 5: Notion API
echo "📝 Phase 5: Notion API"
echo "======================"
echo "1. Notion Developer Portal: https://www.notion.so/my-integrations"
echo "2. New Integration erstellen"
echo "3. API Key kopieren"
echo ""
echo "Benötigte .env Variablen:"
echo "NOTION_API_KEY=secret_..."
echo ""

echo ""
echo "🎯 Nächste Schritte:"
echo "=================="
echo "1. Wähle Phase 1 (WhatsApp) - höchste Priorität"
echo "2. API Keys in .env eintragen"
echo "3. Server-Routen in server.js hinzufügen"
echo "4. Bot Commands erweitern"
echo "5. Testen und validieren"
echo ""
echo "📋 Bereit für Erweiterung? (y/n)"
